name: deploy

on:
  workflow_dispatch:
  
run-name: Upload and transform test

jobs:
  html-to-json:
    runs-on: ubuntu-latest
    outputs:
      file-path: scripts/extractedData.json  # Define la ruta completa de salida
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - run: |
          cd scripts
          bun install
     
      - run: |
          cd scripts
          bun run transform.ts

      - name: Upload generated JSON file
        uses: actions/upload-artifact@v4
        with:
          name: extracted-data
          path: scripts/extractedData.json 

  download-file:
    runs-on: ubuntu-latest
    needs: html-to-json  # Asegura que se ejecute después de `html-to-json`
    steps:
      - name: Download generated file
        uses: actions/download-artifact@v4
        with:
          name: extracted-data
          path: ./downloads  # Descarga el archivo en la carpeta local `downloads`

  call-helper-workflow:
    needs: download-file
    uses: BrandonMDiaz/Budget/.github/workflows/helper.yaml@master  # Llama al workflow externo
    with:
      file-path: ./downloads/extractedData.json  # Ruta donde se descargó el archivo
