name: deploy

on:
  workflow_dispatch:

run-name: Upload and trasnform test

jobs:
  html-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - run: |
          cd scripts
          bun install

      - name: Upload generated JSON file
        uses: actions/upload-artifact@v4
        with:
          name: extracted-data
          path: extractedData.json 

  store-on-s3:
    runs-on: ubuntu-latest
    needs: html-to-json  # Ensures it runs after `html-to-json`
    steps:
      - name: Download generated file
        uses: actions/download-artifact@v4
        with:
          name: extracted-data

      - name: Print JSON contents
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
