name: deploy

on:
  workflow_dispatch:

run-name: test

jobs:
  html-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run script to generate new file
        run: bun scripts/transform.ts

  store-on-s3:
    runs-on: ubuntu-latest
    needs: html-to-json  # Ensures it runs after `html-to-json`
    steps:
      - name: Download generated file
        uses: actions/download-artifact@v3
        with:
          name: extracted-data

      - name: Print JSON contents
        shell: bash
        run: cat extractedData.json
