name: deploy

on:
  workflow_dispatch:
  
run-name: Upload and trasnform test

jobs:
  html-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - run: |
          cd scripts
          bun install
     
      - run: |
          cd scripts
          bun run transform.ts

      - name: Upload generated JSON file
        uses: actions/upload-artifact@v4
        with:
          name: extracted-data
          path: scripts/extractedData.json 

  store-on-s3:
    needs: html-to-json
    runs-on: ubuntu-latest

    steps: 
      - name: download find
        uses: actions/download-artifact@v3  
        with:  
          name: extracted-data  # Name used in the upload step  
      - name: uses workflow
        uses: BrandonMDiaz/Budget/.github/workflows/helper.yaml@master
        with:
          file_path: ""
        secrets: inherit

